export enum EPermission {
  PERMISSION_READ = 'PERMISSION_READ',
  PERMISSION_WRITE = 'PERMISSION_WRITE',
  ROLE_READ = 'ROLE_READ',
  ROLE_WRITE = 'ROLE_WRITE',

  USER_READ = 'USER_READ',
  USER_WRITE = 'USER_WRITE',
}
