export enum EConfig {
  EXMO_JWT_ACCESS_SECRET_KEY = 'EXMO_JWT_ACCESS_SECRET_KEY',
  EXMO_JWT_EXPIRE_TIME = 'EXMO_JWT_EXPIRE_TIME',

  S3_ACCESS_KEY_ID = 'S3_ACCESS_KEY_ID',
  S3_SECRET_ACCESS_KEY = 'S3_SECRET_ACCESS_KEY',
  S3_BUCKET_NAME = 'S3_BUCKET_NAME',

  VERIFICATION_CODE_EXPIRATION_TIME = 'VERIFICATION_CODE_EXPIRATION_TIME',
}
