export enum EConfig {
  PORT = 'PORT',

  EXMO_JWT_ACCESS_SECRET_KEY = 'EXMO_JWT_ACCESS_SECRET_KEY',
  EXMO_JWT_EXPIRE_TIME = 'EXMO_JWT_EXPIRE_TIME',

  S3_ACCESS_KEY_ID = 'S3_ACCESS_KEY_ID',
  S3_SECRET_ACCESS_KEY = 'S3_SECRET_ACCESS_KEY',
  S3_BUCKET = 'S3_BUCKET',
  S3_REGION = 'S3_REGION',

  VERIFICATION_CODE_EXPIRATION_TIME = 'VERIFICATION_CODE_EXPIRATION_TIME',
}
