export enum EConfig {
  EXMO_JWT_ACCESS_SECRET_KEY = 'EXMO_JWT_ACCESS_SECRET_KEY',
  EXMO_JWT_EXPIRE_TIME = 'EXMO_JWT_EXPIRE_TIME',
  VERIFICATION_CODE_EXPIRATION_TIME = 'VERIFICATION_CODE_EXPIRATION_TIME',
}
